# Generated by Django 5.2.17 on 2026-10-06 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(db_index=True, unique=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['retail_price'], name='routing_tru_retail__18db7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='USCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('state_name', models.CharField(db_index=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'US Cities',
                'indexes': [models.Index(fields=['state', 'city'], name='routing_usc_state_ba4e03_idx'), models.Index(fields=['state', 'county', 'city'], name='routing_usc_state_46ae11_idx'), models.Index(fields=['state_name', 'city'], name='routing_usc_state_n_996e3c_idx')],
                'unique_together': {('city', 'state')},
            },
        ),
    ]
