# Generated by Django 5.2.17 on 2026-10-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uscity',
            unique_together={('city', 'state', 'county')},
        ),
    ]
